package com.company;

// Represents a user of the program. Each user can be an employee
// or a customer
public class User {
    int id;
    String name;
    String password;
    boolean loggedIn;

    public User() {
        this.loggedIn = false;
    }

    // creates a new entry in the users database and populates these fields
    // returns the id of the user, also sets logged in to true:
    void register(String name, String password) {
        // TODO: put this info in the database
        this.name = name;
        this.password = password;
        this.loggedIn = true;
        // TODO: get id that is generated by database:
        this.id = -1;
    }

    void login(int id, String password) {
        // TODO: check if id and password match database entry:
        this.loggedIn = true;
    }

}
